### PR TITLE
Fix | V1 Encoded Files In Fixtures

### PR DESCRIPTION
**Pull request by Sammyjo20**
There was an issue which was raised in discussion #148 where if a request returned a downloadable file, the fixture could not be recorded because it threw an exception "Malformed UTF-8 characters, possibly incorrectly encoded"

@derheyne Came up with a brilliant idea to `base64_encode()` the response body if it cannot detect UTF-8 encoding. This is also backwards compatible because of the added `encoding` option.

### CODE REVIEW

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Comment by Sammyjo20** [comment]
@derheyne Let me know if you're happy with this and I'll roll it out

**Comment by derheyne** [comment]
Looks good to me! Thank you so much for the fast implementation :)

Before you merge it let me quickly test it against our code base.

**Comment by derheyne** [comment]
Works perfectly in our code base!

**Comment by Sammyjo20** [comment]
Great thank you for testing!

**Pull request merged**
