### PR TITLE
Renamed $response to $responseClass for better clarity

### PR DESCRIPTION
**Pull request by mstfblci**
Reflects improved naming for better code readability and maintainability

### CODE REVIEW

**Comment by mstfblci** [comment]
If I use withResponse it conflicts with the $response variable in the hasCustomResponses trait so it is important to replace it with $responseClass.

**Comment by mstfblci** [comment]
@Sammyjo20 I also changed the name of the trait for better clarity.

**Comment by Cbrad24** [comment]
This is definitely a breaking change FYI for anyone implementing custom response classes:
https://docs.saloon.dev/the-basics/responses

Neither for or against it but as long as it's known it's breaking.

**Comment by Sammyjo20** [comment]
This is considered a breaking change which I wouldn't be willing to allow until v4 is released.

**Pull request closed without merging**
