### PR TITLE
Feature | V2 - Custom Exception Handlers

### PR DESCRIPTION
**Pull request by Sammyjo20**
Co-authored-by: Tom Witkowski <6187884+Gummibeer@users.noreply.github.com>

### CODE REVIEW

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Comment by Sammyjo20** [comment]
@Gummibeer I have finished the core part of the code now, I've still got to write the 4xx, 5xx exceptions but please could you look through the handler logic and let me know what you think? Thank you!

**Comment by Sammyjo20** [comment]
I've added some more exceptions, including a `ServerException` and `ClientException` :D

**Comment by Gummibeer** [comment]
Looking good so far. 🎉

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Comment by Sammyjo20** [comment]
That's a wrap!

**Pull request merged**
