### PR TITLE
Feature | Add Dependabot config

### PR DESCRIPTION
**Pull request by JonPurvis**
Hey @Sammyjo20 👋 

This PR goes back to the conversation we had on Twitter a few days ago. This is a very basic Dependabot config that could be used for Saloon. One thing I like to have is a restriction on the number of open Dependabot PR's that I have at any one time, I usually go for 5 but whatever works for you 😄

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Hey @JonPurvis 

Thanks for submitting this as a PR, I really appreciate it! And sorry for the delay getting back to you - it’s been a busy couple of weeks but I’m really looking forward to doing some coding with Saloon tomorrow, so I will likely review and merge this tomorrow. 🤠

**Comment by JonPurvis** [comment]
Hey @Sammyjo20 

Don't worry about it, I know the feeling! Thanks for checking it out 🥳

**Review by niladam — APPROVED** [review]
This looks fine to me @Sammyjo20 :)

**Review by Sammyjo20 — APPROVED** [review]
Thanks, Jon!

**Comment by JonPurvis** [comment]
Anytime! 🥳

**Pull request merged**
